language: objective-c
branches:
  only:
    - master
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
jobs:
  include:
  - stage: "Tests"
    script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=10.3.1,name=iPhone SE (1st generation)'
    osx_image: xcode11.6
    name: "iPhone SE (iOS 10.3)"
  - script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=11.4,name=iPhone 7'
    osx_image: xcode11.6
    name: "iPhone 7 (iOS 11.4)"
  - script: xcodebuild clean test -scheme FloatingPanel -workspace FloatingPanel.xcworkspace -destination 'platform=iOS Simulator,OS=12.4,name=iPhone X'
    osx_image: xcode11.6
    name: "iPhone X (iOS 12.4)"
